version: "3.9"

services:
  node_frontend:
    container_name: node_frontend
    restart: always
    build: ./frontend/
    image: node_frontend
    ports:
      - "3000:3000"
    depends_on:
      - eureka-server
      - api-gateway
      - points-service
      - auth-service
  eureka-server:
    container_name: eureka-server
    restart: always
    build: ./eureka-server/
    image: eureka-server
    ports:
      - "8081:8081"
    networks:
      - eureka-network
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8081/eureka"

  api-gateway:
    container_name: api-gateway
    restart: always
    build: ./api-gateway/
    image: api-gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - eureka-network
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8081/eureka"

  points-service:
    container_name: points-service
    restart: always
    build: ./points-service/
    image: points-service
    depends_on:
      - eureka-server
      - api-gateway
      - postgres-db-points
    networks:
      - eureka-network
      - postgres
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8081/eureka"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-points:5432/points"
      - "SPRING_DATASOURCE_USERNAME=admin"
      - "SPRING_DATASOURCE_PASSWORD=root"

  auth-service:
    container_name: auth-service
    restart: always
    build: ./auth-service/
    image: auth-service
    depends_on:
      - eureka-server
      - api-gateway
      - postgres-db-auth
    networks:
      - eureka-network
      - postgres
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8081/eureka"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-auth:5432/auth"
      - "SPRING_DATASOURCE_USERNAME=admin"
      - "SPRING_DATASOURCE_PASSWORD=root"

  postgres-db-points:
    image: postgres:15.5
    container_name: postgres-db-points
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=points
    volumes:
      - postgres-db-points-data:/var/lib/postgresql/data
    networks:
      - postgres

  postgres-db-auth:
    image: postgres:15.5
    container_name: postgres-db-auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth
    volumes:
      - postgres-db-auth-data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgAdmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  eureka-network:
    driver: bridge

volumes:
  postgres-db-points-data:
  postgres-db-auth-data:
  pgadmin-data:

